### ISSUE TITLE
Error occurred when opening the game using the mod

### ISSUE THREAD

**Issue by ustaalon** [AinaVT/LethalConfig#19]
[Info   :   BepInEx] Loading [Custom Emotes API 1.1.8]
[Error  : Unity Log] MissingMethodException: Method not found: void LethalConfig.ConfigItems.Options.FloatSliderOptions.set_Min(single)
Stack trace:
EmotesAPI.Settings.RunAll () (at <45c46f6215af4fed84ced0846465b5b0>:0)
EmotesAPI.CustomEmotesAPI.Awake () (at <45c46f6215af4fed84ced0846465b5b0>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset:OnEnable()

After I copy the error, I saw it might related to another mod/plugin. But its good to know about it

Also opened an issue in [LethalEmotes](https://github.com/Wet-Boys/LethalEmotesAPI/issues/70)

**Comment by AinaVT** [comment]
It's on LethalConfig's end. It was caused due to a recent change.

**Comment by AinaVT** [comment]
@ustaalon Released 1.3.2 with a fix. Could you confirm if it works with that new version?
