### ISSUE TITLE
[Suggestion] LethalConfig does not appear to utilize AcceptableValueLists

### ISSUE THREAD

**Issue by Shaosil** [AinaVT/LethalConfig#29]
I notice that automatic config entires are generated with sliders when there is an AcceptableValueRange provided with the config entry, which is great.

However, some mods (I'll mention my own GeneralImprovements) provide an AcceptableValueList instead, with specific values in mind. For example, the 12 ship monitor entries have very specific string values that they can accept. r2modman shows them, as well as the config file itself, so it would be wonderful if it was implemented (perhaps as a dropdown?) in LethalConfig, because many people have been confused as to what values those entries accept if they do not check the config file.

**Comment by AinaVT** [comment]
Added feature on 1.4.0!
