### ISSUE TITLE
Cannot see other plugins, only LethalConfigs own. And with an error.

### ISSUE THREAD

**Issue by BubblyBall** [AinaVT/LethalConfig#30]
Hey there! I am facing an issue with this plugin. It worked when I first tried it just fine, but when I installed couple of plugins more, and now it's not working. And I do not know how to troubleshoot this issue by myself. It is most likely a mod conflict. I decided to post this here anyway just in case. Here is the error that pops in instantly when the game gets in to the menu.

```
[Info   :   BepInEx] Loading [LethalConfig 1.3.4]
[Info   :ainavt.lc.lethalconfig] Finished loading assets.
[Info   :ainavt.lc.lethalconfig] Registered config "LethalConfig/Example/Int Slider"
[Info   :ainavt.lc.lethalconfig] Registered config "LethalConfig/Example/Float Slider"
[Info   :ainavt.lc.lethalconfig] Registered config "LethalConfig/Example/Float Step Slider"
[Info   :ainavt.lc.lethalconfig] Registered config "LethalConfig/Example/Bool Checkbox"
[Info   :ainavt.lc.lethalconfig] Registered config "LethalConfig/Example/Enum Dropdown"
[Info   :ainavt.lc.lethalconfig] Registered config "LethalConfig/Example/Text Input"
[Info   :ainavt.lc.lethalconfig] Registered config "LethalConfig.ConfigItems.GenericButtonConfigItem"
[Info   :ainavt.lc.lethalconfig] Registered config "LethalConfig/Example/Int Input"
[Info   :ainavt.lc.lethalconfig] Registered config "LethalConfig/Example/Float Input"
[Info   :ainavt.lc.lethalconfig] LethalConfig loaded!
[Info   :ainavt.lc.lethalconfig] Injecting mod config menu into main menu...
[Info   :ainavt.lc.lethalconfig] Injecting mod config menu into main menu...
[Info   :ainavt.lc.lethalconfig] 22 mods loaded: ainavt.lc.lethalconfig;com.elitemastereric.coroner;com.github.mattymatty.LobbyControl;com.rune580.LethalCompanyInputUtils;ControlCompany.ControlCompany;ControlCompanySpoof;discount.alert;FlipMods.LetMeLookDown;FlipMods.TooManyEmotes;gamendegamer.lethaladmin;HDLethalCompany;HoldScanButton;ItemQuickSwitchMod;KoderTech.BoomboxController;Matsuura.HealthMetrics;Miodec.HideChat;NicholaScott.BepInEx.RuntimeNetcodeRPCValidator;MoreEmotes;SpectateEnemy;toemmsen.ChatCommands;twig.latecompany;Zaggy1024.OpenBodyCams

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
LethalConfig.AutoConfig.AutoConfigGenerator.AutoGenerateConfigs () (at D:/UnityProjects/LethalConfig/Assets/Scripts/AutoConfig/AutoConfigGenerator.cs:31)
LethalConfig.LethalConfigManager.AutoGenerateMissingConfigsIfNeeded () (at D:/UnityProjects/LethalConfig/Assets/Scripts/LethalConfigManager.cs:26)
LethalConfig.MonoBehaviours.ConfigMenu.Awake () (at D:/UnityProjects/LethalConfig/Assets/Scripts/MonoBehaviours/ConfigMenu.cs:16)
UnityEngine.Object:Instantiate(GameObject)
LethalConfig.Settings.MenusUtils:InjectMenu(Transform, Transform, GameObject) (at D:/UnityProjects/LethalConfig/Assets/Scripts/Utils/MenusUtils.cs:21)
LethalConfig.Patches.MenuManagerPatches:InjectToMainMenu() (at D:/UnityProjects/LethalConfig/Assets/Scripts/Patches/MenuManagerPatches.cs:40)
LethalConfig.Patches.<DelayedMainMenuInjection>d__1:MoveNext() (at D:/UnityProjects/LethalConfig/Assets/Scripts/Patches/MenuManagerPatches.cs:27)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
```
If this post is made wrong, just delete it. I just started using GH for this post.

**Comment by AinaVT** [comment]
This was an issue that was also brought up on the modding discord. We already have the solution, it'll be fixed on the next version!

**Comment by BubblyBall** [comment]
> This was an issue that was also brought up on the modding discord. We already have the solution, it'll be fixed on the next version!

Okay, that's good to hear! Also I tried the "modman manager" some days ago as I am lazy to install manually a lot of mods. I installed LethalConfig from there, and it works great with all the mods I downloaded thru there. But when I did manual mod install for almost all the same mods I have from the modman right now, then it did not work. But I got no any issues anymore with your mod thru modman manager. Anyway it's great that the issue is addressed and there is a fix coming! If there is issue when installing mods manually.

**Comment by AinaVT** [comment]
> > This was an issue that was also brought up on the modding discord. We already have the solution, it'll be fixed on the next version!
> 
> Okay, that's good to hear! Also I tried the "modman manager" some days ago as I am lazy to install manually a lot of mods. I installed LethalConfig from there, and it works great with all the mods I downloaded thru there. But when I did manual mod install for almost all the same mods I have from the modman right now, then it did not work. But I got no any issues anymore with your mod thru modman manager. Anyway it's great that the issue is addressed and there is a fix coming! If there is issue when installing mods manually.

Yeah, the person that brought it up was also installing mods manually. For some reason, there's a mod or two that when installed like that, whenever auto-generation happens, the mods' instance can not be found, for some reason, and i wasn't accounting for that. I have no idea why manual installations causes this for certain mods.

**Comment by AinaVT** [comment]
Please, if you can, test with the latest version (1.4.0).

**Comment by AinaVT** [comment]
If issue persists after 1.4.0, please feel free to open another issue. Thank you.
