### ISSUE TITLE
I cannot see the names and values of some of the mods

### ISSUE THREAD

**Issue by apeng0907** [AinaVT/LethalConfig#31]
[Info   :ainavt.lc.lethalconfig] 160 mods loaded: .LCMaxSoundsFix;1.Waga.JigglePhysicsPlugin;5Bit.VoiceHUD;Acromata.TwoHanded;ainavt.lc.lethalconfig;atomic.terminalapi;AUniqueName.AlwaysShowClock;bgn.pizzatowerescapemusic;Boniato.Ganimedes;BoomBox.BoomBoxNoPower;BoomboxSyncFix;Chaos.CustomPostProcessingAPI;Chaos.LCCutscene;Chaos.Diversity;cobster.exitdoor;ColtG5.CreepyBrackens;com.elitemastereric.CleanerLogs;com.elitemastereric.coroner;com.elitemastereric.slimetamingfix;com.fumiko.CullFactory;me.swipez.melonloader.morecompany;com.github.lethalmods.lethalexpansioncore;com.github.tinyhoot.ShipLoot;com.github.zehsteam.Hitmarker;evaisa.lethallib;com.rune580.LethalCompanyInputUtils;com.malco.lethalcompany.moreshipupgrades;com.steven.lethalcompany.boomboxmusic;com.zealsprince.locker;Cubly.ColourfulFlashlights;DannyVD.mods.LethalCompany.MonitorLabels;SpectateEnemy;DeadAndBored;DeathAnnounce;dev.kittenji.NavMeshInCompany;discount.alert;doggosuki.Huntdown;DoubleJump.DoubleJump;Dreamweave.CompanyBuildingEnhancements;droneenemy;e3s1.BetterLadders;Electric.IsThisTheWayICame;enemyalert;ENZDS.LockDoorsMod;Ex.MaskStun;FlipMods.FasterItemDropship;FlipMods.HotbarPlus;FlipMods.ObjectVolumeController;FlipMods.ReservedItemSlotCore;FlipMods.ReservedFlashlightSlot;FlipMods.ReservedSprayPaintSlot;FlipMods.ReservedWeaponSlot;FlipMods.TooManyEmotes;flowerwater.watermarkremover;Flowprojects.AoTGiants;GameTranslator;gravydevsupreme.xunity.autotranslator;gravydevsupreme.xunity.resourceredirector;HamCheese.CleanUpCompany;HDLethalCompany;Hexnet.lethalcompany.suitsaver;imabatby.lethallevelloader;ImmortalSnail;ImoutoSama.ScarletMansion;impulse.BetterTotalScrap;Invertigo.JetpackHandling;io.github.CSync;JetpacksCarryBigItems;JigglePhysicsPlugin;KawaiiBone.Remnants;Kittenji.DontTouchMe;Kittenji.HerobrineMod;Kittenji.LaserPointerDetonator;kuba6000.LC_MimicFixMod;lauriichan.friendpatches;LCBetterSaves;LCMOD.MasterKey;lekakid.lcsignaltranslatoraligner;LethalExpansion;LethalNetworkAPI;LethalPosters;LethalPresents;LethalSnapProject;Linkoid.Dissonance.LagFix;MaskedEnemyRework;MCStronghold;me.loaforc.facilitymeltdown;MegaPiggy.BuyableShotgunShells;MentalHospital;Mhz.MoreHead;MiffyL.KillItWithShovel;monke.lc.jumpdelay;NicholaScott.BepInEx.RuntimeNetcodeRPCValidator;MoreEmotes;MoreInteriors;mrgrm7.LethalCasino;MV.NicerTeleporters;nomnom.turret-key;Nyxchrono-DoorBreach;OpJosMod.SaferJetpack;OuterDoorButtons;Ovchinikov.KillableEnemies.Main;Piggy.LCOffice;PingDisplay;PloufJPEG.CompanyCreatures;quackandcheese.togglemute;rafl.BonkHitSfxFixed;rainbow137-NewYearJester;rattenbonkers.TVLoader;rileyzzz.Skibidi;RugbugRedfern.SkinwalkerMod;scin.BrackenPlush;scin.bunkspidPlushie;scin.CoilheadPlushie;scin.ComedymaskPlush;scin.Hoarding-BugPlushPlush;scin.JesterPlushie;scin.TragedymaskPlush;ScoopysVarietyMod;Scopophobia;SCPCBDunGen;ShaosilGaming.GeneralImprovements;ShootableMouthDogs;ShowAmmoCount;SilasMeyer.EnemyLoot;skidz.PoolRooms;SleeplessKyru.SnapRotateFurniture;snake.tech.LCHazardsOutside;SomePriceMod;Spantle.ThrowEverything;Stoneman.LethalProgression;stormytuna.RouteRandom;sugarlo.bepinex.bepinexplugins.chopchopfruit;sugarlo.bepinex.bepinexplugins.flameflamefruit;sugarlo.bepinex.bepinexplugins.gumgumfruit;sugarlo.bepinex.bepinexplugins.opopfruit;sugarlo.bepinex.bepinexplugins.smilefruit;sugarlo.bepinex.bepinexplugins.smokesmokefruit;sunnobunno.YippeeMod;suskitech.LCAlwaysHearActiveWalkie;taffyko.BetterSprayPaint;taffyko.NameplateTweaks;taffyko.NiceChat;TalkingHeads;TheCosmicJesterOfTheVoid.LCGoldenShovelMod;Theronguard.EmergencyDice;TitaniumTurbine.EnemySpawner;tolstj.turretAlwaysLaser;twig.latecompany;veri.lc.shipwindow;viviko.BetterDecorPlacement;viviko.BunkbedRevive;WeatherMultipliers;WeatherTweaks;x753.Mimics;x753.More_Suits;Zaggy1024.NutcrackerFixes;Zaggy1024.OpenBodyCams;Zaggy1024.PathfindingLagFix;Zeus.JustJump
[Warning:ainavt.lc.lethalconfig] No UI component found for config of type Double (Ganimedes/Mp3.AudioVolume/Volume)
[Warning:ainavt.lc.lethalconfig] No UI component found for config of type Color (More Ship Upgrades/Night Vision/Night Vision Color)
[Warning:ainavt.lc.lethalconfig] No UI component found for config of type Color (MonitorLabels/2. Colours/targetLabelColour)
[Warning:ainavt.lc.lethalconfig] No UI component found for config of type Color (MonitorLabels/2. Colours/otherLabelColour)
[Warning:ainavt.lc.lethalconfig] No UI component found for config of type Color (MonitorLabels/2. Colours/deadLabelColour)
[Warning:ainavt.lc.lethalconfig] No UI component found for config of type Color (MonitorLabels/2. Colours/radarBoosterLabelColour)
[Warning:ainavt.lc.lethalconfig] No UI component found for config of type Color (MonitorLabels/2. Colours/enemyLabelColour)
[Warning:ainavt.lc.lethalconfig] No UI component found for config of type Color (MonitorLabels/2. Colours/deadEnemyLabelColour)
[Warning:ainavt.lc.lethalconfig] No UI component found for config of type Color (MonitorLabels/2. Colours/scrapLabelColour)
[Warning:ainavt.lc.lethalconfig] No UI component found for config of type Color (MonitorLabels/2. Colours/highValueScrapLabelColour)
[Warning:ainavt.lc.lethalconfig] No UI component found for config of type Color (MonitorLabels/2. Colours/carriedScrapLabelColour)
[Warning:ainavt.lc.lethalconfig] No UI component found for config of type Color (MonitorLabels/2. Colours/inShipScrapLabelColour)
[Warning:ainavt.lc.lethalconfig] No UI component found for config of type Vector2 (MonitorLabels/4. Label Offsets/radarTargetLabelOffset)
[Warning:ainavt.lc.lethalconfig] No UI component found for config of type Vector2 (MonitorLabels/4. Label Offsets/enemyLabelOffset)
[Warning:ainavt.lc.lethalconfig] No UI component found for config of type Vector2 (MonitorLabels/4. Label Offsets/scrapLabelOffset)
[Info   :ainavt.lc.lethalconfig] Generated 84 mod entries.
[Info   :ainavt.lc.lethalconfig] Generated 1108 configs, of which 1034 were missing and registered.

**Comment by AinaVT** [comment]
Please, if you can, test with the latest version (1.4.0).

**Comment by AinaVT** [comment]
If issue persists after 1.4.0, please feel free to open another issue. Thank you.
