### ISSUE TITLE
How to change the logo in config?

### ISSUE THREAD

**Issue by PC-Principal** [AinaVT/LethalConfig#37]
Hello!

Have a question, how to change the logo of your mod inside the game? 

There the image is a question mark, I don’t really understand how this can be done.

**Comment by FerusGrim** [comment]
`LethalConfigManager#SetModIcon` takes a `UnityEngine.Sprite` parameter.

**Comment by AinaVT** [comment]
LethalConfig attempts to use the icon that thunderstore uses (the `icon.png` file you upload together with your manifest), so if you're testing without them, it won't be able to find it and replace with a question mark placeholder.

You can also use what Ferus said, passing the image as a `UnityEngine.Sprite` to the `SetModIcon` method.

**Comment by PC-Principal** [comment]
> LethalConfig attempts to use the icon that thunderstore uses (the `icon.png` file you upload together with your manifest), so if you're testing without them, it won't be able to find it and will replace it with a question mark placeholder.
> 
> You can also use what Ferus said, passing the image as a `UnityEngine.Sprite` to the `SetModIcon` method.

Thank you, yes - I test separately, probably for this reason there is no logo
