### ISSUE TITLE
configs of some mods do not appear in the lethal config menu

### ISSUE THREAD

**Issue by n0souls** [AinaVT/LethalConfig#40]
hi there. I have many mods, and among them there are mods that used to appear in the lethal config settings menu, but now they don’t. I saw a similar issue, but it was two months ago, and it says that you will fix this with the release of the update. I have the latest version, and in the menu I have two of your mods plus reactor meltdown, and other mods like better stamina are simply missing. I tried deleting all the configs, tried reinstalling your mod, installing the old version - it didn’t help.
[LogOutput.log](https://github.com/AinaVT/LethalConfig/files/14731580/LogOutput.log)

**Comment by AinaVT** [comment]
Please, if you can, test with the latest version (1.4.0).

**Comment by AinaVT** [comment]
If issue persists after 1.4.0, please feel free to open another issue. Thank you.
