### ISSUE TITLE
Expose BaseConfigItem#ChangeToDefault  or implement own 'Reset All' button

### ISSUE THREAD

**Issue by FerusGrim** [AinaVT/LethalConfig#41]
I was in the process of creating a 'Reset All' config button:

```cs
        RegistryButtonEntry("Actions", "Reset All", "Reset all settings to default", () =>
        {
            foreach (var item in _configItems) item.ChangeToDefault();
        });
```

However, [`BaseConfigItem#ChangeToDefault`](https://github.com/AinaVT/LethalConfig/blob/main/Assets/Scripts/ConfigItems/BaseConfigItem.cs#L57) is an internal method.

I would suggest exposing this, but then it also may make more sense to just implement your own version of a 'Reset All' button, but I am unaware of your plans, so. 😄

**Comment by FerusGrim** [comment]
@AinaVT The basic request of exposing BaseConfigItem#ChangeToDefault was completed in 87f77f92a76abed918dabde0e34b0c58cad5a82f. I'll leave it up to your discretion on whether or not you consider this completed or if you want to consider this an enhancement suggestion for a native 'Reset All' button.

**Comment by AinaVT** [comment]
@FerusGrim I'll probably release a minor version later tonight with that change and a memory-optimization thing someone brought up on discord, then i'll mark this as closed and open another myself for a built-in button since i did want to do that.
