### ISSUE TITLE
All mods doesn't appear in the mod config 

### ISSUE THREAD

**Issue by TsamT** [AinaVT/LethalConfig#43]
There is an issue that the mods doesn't appear in the mod configuration in the latest update (1.4.0)

**Comment by AinaVT** [comment]
I'm not sure if you closed the issue by accident, but if it's still happening, could you provide a profile code for testing?

**Comment by TsamT** [comment]
@AinaVT I closed it because I tried to fix the bug and it ended up working so I closed it
