### ISSUE TITLE
Unable to post as a PR, so here's a fork 😁 

### ISSUE THREAD

**Issue by darmuh** [AinaVT/LethalConfig#52]
Hello,

I've been messing with adding some things to LethalConfig since it hasn't been updated in a while and there's some features I wanted to see included. It's probably not the cleanest implementation but I still wanted to submit it as a PR. 

Unfortunately I was unable to post this as a PR as I am not designated as a collaborator. So instead I forked the repo and am now submitting this issue for you to see. I posted a video of the below changes in the modding discord if you'd like to see how they work.

Changes:
- Added config item to add a "show/hide" button to section headers.
- Adjusted header appearance slightly (smaller & will now add ellipses to sections that have too long of a name)
- Made it so string configs with "acceptable values" now correctly create dropdown config buttons automatically
- Added some methods for adding config files that were generated later than awake (such as LLL & LethalConstellations)

Link to fork - https://github.com/darmuh/LethalConfig

**Comment by AinaVT** [comment]
You should be able to open a PR from your fork into this repo, other people did without me doing anything regarding designating them as collaborators. Unless there's a setting i'm unaware of.

**Comment by darmuh** [comment]
Yep that worked my bad. Skill issue on my part not knowing the proper process for submitting a PR 😓 

here’s the PR link https://github.com/AinaVT/LethalConfig/pull/53#issue-2520450751
